### ISSUE TITLE
I can't get it to update the IP with freedns, and I don't know why...

### ISSUE THREAD

**Issue by EnriqueBesuman** [joweisberg/docker-dynamic-dns#10]
This is the log:

[2024-05-27 06:51:49] curl -H "User-Agent: no-ip shell script/1.0 mail@mail.com" -H "Authorization: Basic ZW5yaXF1ZS5iZXN1bWFuQGdtYWlsLmNvbTpYTmtTS2cyVHJDOGlfKkE=" 
curl: (2) no URL specified
curl: try 'curl --help' or 'curl --manual' for more information

And this is my docker-compose:

version: "3.5"

services:

  dynamicdns:
    container_name: dynamicdns
    image: joweisberg/dynamic-dns:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - USER=${FREEDNS_USR}
      - PASSWORD=${FREEDNS_PASSWORD}
      - SERVICE=freedns
      - HOSTNAME=${FREEDNS_HOSTNAME}
      - DETECTIP=1
      - INTERVAL=10
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5

    labels: # Labels para What's up Docker
      - wud.display.name=DynamicDNS
      - wud.display.icon=mdi:dns-outline

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.160.0/20

Of course, the username, password and URL, checked and correct, I don't know what could be happening... Can you help me with this please?

Thanks!!

**Comment by joweisberg** [comment]
Hello
The issue is fixed, can you check by pulling lates image version?
Thanks to you

**Comment by joweisberg** [comment]
Fix issue curl: (2) no URL specified

**Comment by EnriqueBesuman** [comment]
Now changing the IP works, thank you very much!
But I'm not sure if curls in which the IP does not change should be considered an error, perhaps it should be marked as info...

ERROR: Address XXX.XXX.XXX.XXX has not changed.

Thank you very much again!!

**Comment by joweisberg** [comment]
This is message return by curl command: ERROR: Address XXX.XXX.XXX.XXX has not changed.
I'm glad the issue is fixed
Enjoy
