### ISSUE TITLE
cURL returns error when updating DuckDNS

### ISSUE THREAD

**Issue by norweeg** [joweisberg/docker-dynamic-dns#3]
when using your image to update DuckDNS, cURL returns the following error:

`curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)`

**Comment by joweisberg** [comment]
Do you use USER=<your_login> or <your_email_address> with PASSWORD=< token > ?

**Comment by norweeg** [comment]
not exactly sure what you're asking, but yes, I am passing USER as my email address and my token as PASSWORD in my environment

**Comment by joweisberg** [comment]
It's now fixed, please pull latest version
Set 
- SERVICE=duckdns
- USER=< your email address >
- PASSWORD=< your token >
- HOSTNAME=< sub.duckdns.org >
