### ISSUE TITLE
myexternalip.com incorrectly resolving ip address

### ISSUE THREAD

**Issue by norweeg** [joweisberg/docker-dynamic-dns#4]
the service your script uses to detect external ip addresses started incorrectly resolving my external ip address.  Unsure if this is a problem just affecting me, however, no other comparable service is getting it wrong.  This just started happening today.   I would recommend changing the API you're using to something more reliable and also open-source e.g. https://github.com/rdegges/ipify-api

**Comment by pmontgo33** [comment]
I also started having this issue today

**Comment by norweeg** [comment]
the service seems to be resolving ip addresses correctly again, but I think it is still worth switching how this container does that function: ipify is very big/popular, open source, and can resolve both ipv4 and ipv6 addresses whereas the container uses a different service for ipv6 (which also happens to be completely unavailable right now)

**Comment by joweisberg** [comment]
No issue so far
I will check to implement ipify in futur release
